# Generated by Django 2.2.20 on 2021-12-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0037_layer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='eovs',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='readiness_coordination',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='readiness_data',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='readiness_requirements',
        ),
    ]
