# Generated by Django 2.2.20 on 2022-04-28 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('layers', '0039_layer_sops'), ('layers', '0040_auto_20220428_0747'), ('layers', '0041_auto_20220428_0900'), ('layers', '0042_auto_20220428_0913'), ('layers', '0043_auto_20220428_1002')]

    dependencies = [
        ('layers', '0038_auto_20211210_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='sops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='List of SOP URLs, comma separated.', null=True, size=None, verbose_name='SOPs'),
        ),
    ]
