# Generated by Django 2.2.20 on 2022-04-28 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0039_layer_sops_squashed_0043_auto_20220428_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='outputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='List of outputs (products, applications), comma separated URLs.', null=True, size=None, verbose_name='Outputs'),
        ),
    ]
