# Generated by Django 2.2.20 on 2022-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0040_layer_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='obis_pub_interest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
