# Generated by Django 2.2.20 on 2022-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0041_layer_obis_pub_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='obis_pub_interest',
            field=models.BooleanField(blank=True, null=True, verbose_name='Interest in publishing to OBIS'),
        ),
    ]
