# Generated by Django 2.2.20 on 2022-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0042_auto_20220428_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='in_obis',
            field=models.BooleanField(blank=True, null=True, verbose_name='In OBIS'),
        ),
    ]
