# Generated by Django 2.2.20 on 2022-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0043_layer_in_obis'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='funding',
            field=models.TextField(blank=True, null=True, verbose_name='Funding'),
        ),
    ]
