# Generated by Django 2.2.20 on 2022-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0045_layer_funding_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='data_in_obis',
            field=models.CharField(blank=True, choices=[('no', 'No; none of the biological data collected by the network is included in OBIS'), ('some', 'Yes; some of the biological data collected by the network is included in OBIS'), ('all', 'Yes; all of the biological data collected by the network is included in OBIS')], max_length=30, null=True),
        ),
    ]
