# Generated by Django 2.2.20 on 2022-07-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0046_layer_data_in_obis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='in_obis',
        ),
    ]
