# Generated by Django 2.2.20 on 2021-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eov',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
