# Generated by Django 2.2.20 on 2021-12-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0038_auto_20211210_1440'),
        ('goos', '0002_eov_short_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eov',
        ),
    ]
